// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Property struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   int64              `json:"owner_id"`
	Title     string             `json:"title"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Reservation struct {
	ID           int64              `json:"id"`
	PropertyID   pgtype.UUID        `json:"property_id"`
	PropertyName string             `json:"property_name"`
	BookedBy     int64              `json:"booked_by"`
	GuestName    string             `json:"guest_name"`
	CheckIn      pgtype.Timestamptz `json:"check_in"`
	CheckOut     pgtype.Timestamptz `json:"check_out"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Type         string             `json:"type"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	Postcode     pgtype.Text        `json:"postcode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
