// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOverlappingReservations = `-- name: CheckOverlappingReservations :one
SELECT COUNT(*)
FROM reservations
WHERE property_id = $1
  AND check_out > $2
  AND check_in < $3
`

type CheckOverlappingReservationsParams struct {
	PropertyID  pgtype.UUID        `json:"property_id"`
	NewCheckIn  pgtype.Timestamptz `json:"new_check_in"`
	NewCheckOut pgtype.Timestamptz `json:"new_check_out"`
}

func (q *Queries) CheckOverlappingReservations(ctx context.Context, arg CheckOverlappingReservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkOverlappingReservations, arg.PropertyID, arg.NewCheckIn, arg.NewCheckOut)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPropertiesByOwner = `-- name: CountPropertiesByOwner :one
SELECT COUNT(*)
FROM properties
WHERE owner_id = $1
`

func (q *Queries) CountPropertiesByOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPropertiesByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (owner_id, title, address)
VALUES ($1, $2, $3)
RETURNING id, owner_id, title, address, created_at, updated_at
`

type CreatePropertyParams struct {
	OwnerID int64  `json:"owner_id"`
	Title   string `json:"title"`
	Address string `json:"address"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty, arg.OwnerID, arg.Title, arg.Address)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (property_id, property_name, booked_by, guest_name, check_in, check_out)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, property_id, property_name, booked_by, guest_name, check_in, check_out, created_at, updated_at
`

type CreateReservationParams struct {
	PropertyID   pgtype.UUID        `json:"property_id"`
	PropertyName string             `json:"property_name"`
	BookedBy     int64              `json:"booked_by"`
	GuestName    string             `json:"guest_name"`
	CheckIn      pgtype.Timestamptz `json:"check_in"`
	CheckOut     pgtype.Timestamptz `json:"check_out"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.PropertyID,
		arg.PropertyName,
		arg.BookedBy,
		arg.GuestName,
		arg.CheckIn,
		arg.CheckOut,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.PropertyName,
		&i.BookedBy,
		&i.GuestName,
		&i.CheckIn,
		&i.CheckOut,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, type, created_at, updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Type         string `json:"type"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Type,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getPropertyByID = `-- name: GetPropertyByID :one
SELECT id, owner_id, title, address, created_at, updated_at
FROM properties
WHERE id = $1
`

func (q *Queries) GetPropertyByID(ctx context.Context, id pgtype.UUID) (Property, error) {
	row := q.db.QueryRow(ctx, getPropertyByID, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.user_id, s.token, s.expires_at, s.created_at,
       u.id AS u_id, u.name AS u_name, u.email AS u_email, u.type AS u_type
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > now()
`

type GetSessionByTokenRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UID       int64              `json:"u_id"`
	UName     string             `json:"u_name"`
	UEmail    string             `json:"u_email"`
	UType     string             `json:"u_type"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UID,
		&i.UName,
		&i.UEmail,
		&i.UType,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, type, address_line_1, address_line_2, postcode, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Type,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Postcode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagerReservationsFiltered = `-- name: ListManagerReservationsFiltered :many
SELECT r.id, r.property_id, r.property_name, r.booked_by, r.guest_name, r.check_in, r.check_out, r.created_at, r.updated_at,
       COUNT(*) OVER() AS total_count
FROM reservations r
JOIN properties p ON r.property_id = p.id
WHERE p.owner_id = $1
  AND ($2::text IS NULL OR r.property_name ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR r.guest_name ILIKE '%' || $3::text || '%')
  AND ($4::timestamptz IS NULL OR r.check_in >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR r.check_out <= $5::timestamptz)
ORDER BY r.created_at DESC
LIMIT $7 OFFSET $6
`

type ListManagerReservationsFilteredParams struct {
	OwnerID            int64              `json:"owner_id"`
	PropertyNameFilter pgtype.Text        `json:"property_name_filter"`
	GuestNameFilter    pgtype.Text        `json:"guest_name_filter"`
	CheckInFrom        pgtype.Timestamptz `json:"check_in_from"`
	CheckOutTo         pgtype.Timestamptz `json:"check_out_to"`
	Off                int32              `json:"off"`
	Lim                int32              `json:"lim"`
}

type ListManagerReservationsFilteredRow struct {
	ID           int64              `json:"id"`
	PropertyID   pgtype.UUID        `json:"property_id"`
	PropertyName string             `json:"property_name"`
	BookedBy     int64              `json:"booked_by"`
	GuestName    string             `json:"guest_name"`
	CheckIn      pgtype.Timestamptz `json:"check_in"`
	CheckOut     pgtype.Timestamptz `json:"check_out"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListManagerReservationsFiltered(ctx context.Context, arg ListManagerReservationsFilteredParams) ([]ListManagerReservationsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listManagerReservationsFiltered,
		arg.OwnerID,
		arg.PropertyNameFilter,
		arg.GuestNameFilter,
		arg.CheckInFrom,
		arg.CheckOutTo,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagerReservationsFilteredRow
	for rows.Next() {
		var i ListManagerReservationsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.PropertyName,
			&i.BookedBy,
			&i.GuestName,
			&i.CheckIn,
			&i.CheckOut,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesByOwner = `-- name: ListPropertiesByOwner :many
SELECT id, owner_id, title, address, created_at, updated_at
FROM properties
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPropertiesByOwnerParams struct {
	OwnerID int64 `json:"owner_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPropertiesByOwner(ctx context.Context, arg ListPropertiesByOwnerParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, listPropertiesByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
